services:
  auth-service:
    build:
      context: ./auth-service
    container_name: lenovo-auth-service
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env
    restart: unless-stopped

  catalog-service:
    build:
      context: ./catalog-service
    container_name: lenovo-catalog-service
    ports:
      - "8002:8000"
    env_file:
      - ./catalog-service/.env
    restart: unless-stopped

  sales-service:
    build:
      context: ./sales-service
    container_name: lenovo-sales-service
    ports:
      - "8003:8000"
    env_file:
      - ./sales-service/.env
    depends_on:
      - catalog-service
    restart: unless-stopped